### ISSUE TITLE
Possible Calc Error?

### ISSUE THREAD

**Issue by frankvg** [apach3guy/CAN3#1]
Thanks for putting this up! 

In looking at the calculations in logger.py, under SHOW _REAR_POWER_DATA, the calculations (3 of them) maybe wrong, but I can't confirm it. For example:
 mechPower = ((message.data[2] + ((message.data[3] & 0x7)<<8))-(512 \* (message.data[3] & 0x4))) / 2

It seems wrong that data[3] bits 0,1 and 2 (i.e. &7) are used in the first part of the equation, and then data[3] bit 2 (i.e. & 0x4) is re-used in the latter part. I'd expect different bits.  The other two similar calculations torqMeas and torqEst also reuse bits in a similar way, which seems wrong. If you have a source document, you might check if this was done wrong.

**Comment by obrien28** [comment]
@frankvg Almost all of the decodes come from [this document](http://skie.net/uploads/TeslaCAN/) by wk057, see page five ID 266 for the encoding, I just checked it again and it's correct. I use it in my own python application and have successfully tested it in-car.

**Comment by frankvg** [comment]
I see it's the same as wk057's decode. I'll likely ask wk057 about it, but thanks for checking and confirming it's working as expected. Still seems strange to me. Just part of the life of dealing with undocumented areas of the Tesla!
